### ISSUE TITLE
wrap the text and increase the box width and length

### ISSUE THREAD

**Issue by mrunalnshah** [AsgarDatari/ChatWeb#27]
currently big text are out of the box and goes beyond our code expectatiaion. i know spelling is wrong. ah i dont know how to explain so here is the photo.
![image](https://github.com/AsgarDatari/ChatWeb/assets/108453611/1118388d-85ea-4a9b-aa9e-0887ae08b632)

**Comment by aaquifqureshi** [comment]
added  " overflow-wrap: break-word; " in .message{ } in css file
